
Description:  Jacob Farner Test Generic EC2 Public Instance with Wordpress Bootstrap. Requires VPC subnets from JFT-VPC.  

Parameters:
  LatestAmiId:
    Description: AMI for Bastion Host (default is latest AmaLinux2)
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of an existing SSH Keypair to access the instance"
  DBName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Default: jftwordpress
    Description: The WordPress database name
    MaxLength: '64'
    MinLength: '1'
    Type: String
  DBPassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: WordPress database admin account password
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DBRootPassword:
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
    Description: MySQL root password
    MaxLength: '41'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  DBUser:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
    Description: The WordPress database admin account username
    Default: jftwordpress
    MaxLength: '16'
    MinLength: '1'
    NoEcho: 'true'
    Type: String
Resources:
  Wordpress:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: "t2.micro"
      ImageId: !Ref LatestAmiId
      IamInstanceProfile: !Ref SessionManagerInstanceProfile
      SubnetId: !ImportValue jft-vpc1-subnet-weba
      SecurityGroupIds: 
        - !ImportValue jft-vpc1-default-instance-sg
      Tags:
        - Key: Name
          Value: JFT-Wordpress
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          #Checking for updates
          yum -y update
          yum -y upgrade
          #Installing system software - MariaDB running on Apache web server.
          sudo yum install -y mariadb-server httpd wget
          sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
          #Enable software for current session and configure to execute on startup
          sudo systemctl enable httpd
          sudo systemctl enable mariadb
          sudo systemctl start httpd
          sudo systemctl start mariadb
          #Assign root password credential for MariaDB
          mysqladmin -u root password $DBRootPassword
          #Install latest version of Wordpress. remove unnecessary folders.
          sudo wget http://wordpress.org/latest.tar.gz -P /var/www/html
          cd /var/www/html
          sudo tar -zxvf latest.tar.gz
          sudo cp -rvf wordpress/* .
          sudo rm -R wordpress
          sudo rm latest.tar.gz
          #Credentials are assigned in the wordpress configuration
          sudo cp ./wp-config-sample.php ./wp-config.php
          sudo sed -i "s/'database_name_here'/'$DBName'/g" wp-config.php
          sudo sed -i "s/'username_here'/'$DBUser'/g" wp-config.php
          sudo sed -i "s/'password_here'/'$DBPassword'/g" wp-config.php   
          sudo chown apache:apache * -R
          #Granting permissions for configuration files
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          #Create temporary file to contain commands for setting up MariaDB instance on the instance
          echo "CREATE DATABASE $DBName;" >> /tmp/db.setup
          echo "CREATE USER '$DBUser'@'localhost' IDENTIFIED BY '$DBPassword';" >> /tmp/db.setup
          echo "GRANT ALL ON $DBName.* TO '$DBUser'@'localhost';" >> /tmp/db.setup
          echo "FLUSH PRIVILEGES;" >> /tmp/db.setup
          #Execute commands from the setup file 
          mysql -u root --password=$DBRootPassword < /tmp/db.setup
          #Remove temporary setup file so that sensitive credentials aren't sitting around
          sudo rm /tmp/db.setup
  SessionManagerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - 'ssm:DescribeAssociation'
                  - 'ssm:GetDeployablePatchSnapshotForInstance'
                  - 'ssm:GetDocument'
                  - 'ssm:DescribeDocument'
                  - 'ssm:GetManifest'
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                  - 'ssm:ListAssociations'
                  - 'ssm:ListInstanceAssociations'
                  - 'ssm:PutInventory'
                  - 'ssm:PutComplianceItems'
                  - 'ssm:PutConfigurePackageResult'
                  - 'ssm:UpdateAssociationStatus'
                  - 'ssm:UpdateInstanceAssociationStatus'
                  - 'ssm:UpdateInstanceInformation'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'ssmmessages:CreateControlChannel'
                  - 'ssmmessages:CreateDataChannel'
                  - 'ssmmessages:OpenControlChannel'
                  - 'ssmmessages:OpenDataChannel' 
                Resource: '*'
              - Effect: Allow
                Action: 
                  - 'ec2messages:AcknowledgeMessage'
                  - 'ec2messages:DeleteMessage'
                  - 'ec2messages:FailMessage'
                  - 'ec2messages:GetEndpoint'
                  - 'ec2messages:GetMessages'
                  - 'ec2messages:SendReply'
                Resource: '*'
  SessionManagerInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref SessionManagerRole